FROM simonfong6/deep-learning:9.0-cudnn7-devel-ubuntu16.04-tensorflow-gpu

LABEL repository simonfong6/deep-learning
LABEL tag 9.0-cudnn7-devel-ubuntu16.04-tensorflow-gpu-keras

RUN pip3 install keras